# Generated by Django 4.0.1 on 2022-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Url",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_url", models.URLField(max_length=5000)),
                ("short_url", models.URLField(max_length=500)),
            ],
        ),
    ]
